Sprint 2
ClevertecFrontendLab/sprint2-Dubrik90 pull request #1
Opened 2023-02-09 19:24 UTC by Dubrik90

2023-02-09 19:29 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675970993/slider%20one%20foto%20768px.png)

2023-02-09 20:05 UTC, Ivan6813 requested changes

2023-02-09 20:05 UTC, Ivan6813 commented on .editorconfig
> +insert_final_newline = true
![Screenshot_20230209_225747_com android chrome](https://user-images.githubusercontent.com/79784960/217923911-70ee3c20-25d0-4367-b5f8-7e512b9fa9ec.jpg)
![Screenshot_20230209_225722_com android chrome](https://user-images.githubusercontent.com/79784960/217923919-887522a0-7f08-46a4-b828-640ec98557ac.jpg)
Обрати внимание на скриншоты, как они выглядят, очень сложно что-то разобрать там. Скорее всего проблема в том, что у тебя хедер имеет position sticky. Надо бы исправить, что бы скриншоты нормально выглядили

2023-02-09 20:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675974640/slider%20one%20foto%20768px.png)

2023-02-09 20:32 UTC, Dubrik90 commented
удалил один sticky (он не работал) и закоментировал все transition. локально работает.

2023-02-09 22:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dubrik90/1675980160/slider%20one%20foto%20768px.png)

2023-02-10 05:46 UTC, Ivan6813 approved these changes

2023-02-10 05:46 UTC, Ivan6813 commented on .editorconfig
> +indent_style = space
Все равно проблема осталась. Ставлю апрув, но под твою ответственность, что ты найдёшь в чем причина и исправишь, что бы в следующем спринте скрины выглядили нормально) только не докидывай этот фикс в этот ПР, мержи как есть, а зальешь уже на третьем спринте

2023-02-10 05:52 UTC, merged